In [1]:
#analyze, manipulate, helps you get data ready for machine learning

import pandas as pd
import numpy as np

names = pd.Series(["julen","jayson","aveg"])
print(names)

0     julen
1    jayson
2      aveg
dtype: object

In [6]:

Type = pd.Series(["thin","tall","fat"])
sur_name = pd.Series(["Shrestha","Pradhanangay","fatto"])

names_data = pd.DataFrame({"Name": names ,  "last_name" : sur_name ,"body-type": Type})
names_data

     Name     last_name body-type
0   julen      Shrestha      thin
1  jayson  Pradhanangay      tall
2    aveg         fatto       fat

In [17]:
data = pd.read_csv("../Data/data.csv")
data

,element,round,assists,bonus,bps,clean_sheets,value,creativity,total_points,goals_conceded,...,npxGA_opponent_team,deep_opponent_team,deep_allowed_opponent_team,scored_opponent_team,missed_opponent_team,npxGD_opponent_team,ppda_att_opponent_team,ppda_def_opponent_team,ppda_allowed_att_opponent_team,ppda_allowed_def_opponent_team
0,454,1,0.10863,0.32589,17.788171,0.298733,5.5,0.0,3.611949,1.357876,...,1.094252,9.315789,5.105263,1.552632,1.394737,0.239271,213.236842,25.0,272.026316,27.0
1,454,2,0.00000,0.00000,0.000000,0.000000,5.5,0.0,0.000000,0.000000,...,1.911050,3.000000,4.000000,1.000000,3.000000,-1.388203,351.000000,24.0,263.000000,25.0
2,454,3,0.00000,0.00000,0.000000,0.000000,5.4,0.0,0.000000,0.000000,...,0.549491,9.000000,3.000000,4.000000,1.000000,0.861319,208.000000,44.0,253.000000,19.0
3,454,4,0.00000,0.00000,0.000000,0.000000,5.4,0.0,0.000000,0.000000,...,1.271540,8.000000,11.000000,1.000000,3.000000,-0.193790,286.000000,29.0,204.000000,29.0
4,454,5,0.00000,0.00000,0.000000,0.000000,5.4,0.0,0.000000,0.000000,...,0.986511,4.000000,8.000000,0.000000,1.000000,0.496959,224.000000,21.0,130.000000,19.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71592,27,34,0.00000,0.00000,0.000000,0.000000,4.3,0.0,0.000000,0.000000,...,0.760443,15.000000,1.000000,5.000000,2.000000,1.110977,135.000000,15.0,344.000000,15.0
71593,27,35,0.00000,0.00000,0.000000,0.000000,4.3,0.0,0.000000,0.000000,...,2.657530,7.000000,8.000000,2.000000,3.000000,-1.369330,336.000000,24.0,192.000000,26.0
71594,27,36,0.00000,0.00000,0.000000,0.000000,4.3,0.0,0.000000,0.000000,...,2.106070,3.000000,4.000000,0.000000,3.000000,-1.819509,354.000000,19.0,287.000000,20.0
71595,27,37,0.00000,0.00000,0.000000,0.000000,4.3,0.0,0.000000,0.000000,...,2.223300,4.000000,12.000000,2.000000,1.000000,-0.908140,306.000000,18.0,139.000000,29.0
71596,27,38,0.00000,0.00000,0.000000,0.000000,4.3,0.0,0.000000,0.000000,...,0.984161,2.000000,13.000000,1.000000,1.000000,-0.455239,241.000000,18.0,237.000000,20.0

In [24]:
data.to_csv("../Data/Exported-data-false.csv",index = False)
data.to_csv("../Data/Exported-data-true.csv")
new_data_true = pd.read_csv("../Data/Exported-data-true.csv")
new_data_false = pd.read_csv("../Data/Exported-data-false.csv")

In [23]:
new_data_false

,element,round,assists,bonus,bps,clean_sheets,value,creativity,total_points,goals_conceded,...,npxGA_opponent_team,deep_opponent_team,deep_allowed_opponent_team,scored_opponent_team,missed_opponent_team,npxGD_opponent_team,ppda_att_opponent_team,ppda_def_opponent_team,ppda_allowed_att_opponent_team,ppda_allowed_def_opponent_team
0,454,1,0.10863,0.32589,17.788171,0.298733,5.5,0.0,3.611949,1.357876,...,1.094252,9.315789,5.105263,1.552632,1.394737,0.239271,213.236842,25.0,272.026316,27.0
1,454,2,0.00000,0.00000,0.000000,0.000000,5.5,0.0,0.000000,0.000000,...,1.911050,3.000000,4.000000,1.000000,3.000000,-1.388203,351.000000,24.0,263.000000,25.0
2,454,3,0.00000,0.00000,0.000000,0.000000,5.4,0.0,0.000000,0.000000,...,0.549491,9.000000,3.000000,4.000000,1.000000,0.861319,208.000000,44.0,253.000000,19.0
3,454,4,0.00000,0.00000,0.000000,0.000000,5.4,0.0,0.000000,0.000000,...,1.271540,8.000000,11.000000,1.000000,3.000000,-0.193790,286.000000,29.0,204.000000,29.0
4,454,5,0.00000,0.00000,0.000000,0.000000,5.4,0.0,0.000000,0.000000,...,0.986511,4.000000,8.000000,0.000000,1.000000,0.496959,224.000000,21.0,130.000000,19.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71592,27,34,0.00000,0.00000,0.000000,0.000000,4.3,0.0,0.000000,0.000000,...,0.760443,15.000000,1.000000,5.000000,2.000000,1.110977,135.000000,15.0,344.000000,15.0
71593,27,35,0.00000,0.00000,0.000000,0.000000,4.3,0.0,0.000000,0.000000,...,2.657530,7.000000,8.000000,2.000000,3.000000,-1.369330,336.000000,24.0,192.000000,26.0
71594,27,36,0.00000,0.00000,0.000000,0.000000,4.3,0.0,0.000000,0.000000,...,2.106070,3.000000,4.000000,0.000000,3.000000,-1.819509,354.000000,19.0,287.000000,20.0
71595,27,37,0.00000,0.00000,0.000000,0.000000,4.3,0.0,0.000000,0.000000,...,2.223300,4.000000,12.000000,2.000000,1.000000,-0.908140,306.000000,18.0,139.000000,29.0
71596,27,38,0.00000,0.00000,0.000000,0.000000,4.3,0.0,0.000000,0.000000,...,0.984161,2.000000,13.000000,1.000000,1.000000,-0.455239,241.000000,18.0,237.000000,20.0

In [25]:

new_data_true

,Unnamed: 0,element,round,assists,bonus,bps,clean_sheets,value,creativity,total_points,...,npxGA_opponent_team,deep_opponent_team,deep_allowed_opponent_team,scored_opponent_team,missed_opponent_team,npxGD_opponent_team,ppda_att_opponent_team,ppda_def_opponent_team,ppda_allowed_att_opponent_team,ppda_allowed_def_opponent_team
0,0,454,1,0.10863,0.32589,17.788171,0.298733,5.5,0.0,3.611949,...,1.094252,9.315789,5.105263,1.552632,1.394737,0.239271,213.236842,25.0,272.026316,27.0
1,1,454,2,0.00000,0.00000,0.000000,0.000000,5.5,0.0,0.000000,...,1.911050,3.000000,4.000000,1.000000,3.000000,-1.388203,351.000000,24.0,263.000000,25.0
2,2,454,3,0.00000,0.00000,0.000000,0.000000,5.4,0.0,0.000000,...,0.549491,9.000000,3.000000,4.000000,1.000000,0.861319,208.000000,44.0,253.000000,19.0
3,3,454,4,0.00000,0.00000,0.000000,0.000000,5.4,0.0,0.000000,...,1.271540,8.000000,11.000000,1.000000,3.000000,-0.193790,286.000000,29.0,204.000000,29.0
4,4,454,5,0.00000,0.00000,0.000000,0.000000,5.4,0.0,0.000000,...,0.986511,4.000000,8.000000,0.000000,1.000000,0.496959,224.000000,21.0,130.000000,19.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71592,71592,27,34,0.00000,0.00000,0.000000,0.000000,4.3,0.0,0.000000,...,0.760443,15.000000,1.000000,5.000000,2.000000,1.110977,135.000000,15.0,344.000000,15.0
71593,71593,27,35,0.00000,0.00000,0.000000,0.000000,4.3,0.0,0.000000,...,2.657530,7.000000,8.000000,2.000000,3.000000,-1.369330,336.000000,24.0,192.000000,26.0
71594,71594,27,36,0.00000,0.00000,0.000000,0.000000,4.3,0.0,0.000000,...,2.106070,3.000000,4.000000,0.000000,3.000000,-1.819509,354.000000,19.0,287.000000,20.0
71595,71595,27,37,0.00000,0.00000,0.000000,0.000000,4.3,0.0,0.000000,...,2.223300,4.000000,12.000000,2.000000,1.000000,-0.908140,306.000000,18.0,139.000000,29.0
71596,71596,27,38,0.00000,0.00000,0.000000,0.000000,4.3,0.0,0.000000,...,0.984161,2.000000,13.000000,1.000000,1.000000,-0.455239,241.000000,18.0,237.000000,20.0

In [26]:
data.index

RangeIndex(start=0, stop=71597, step=1)

In [27]:
data_columns = data.columns
data_columns

Index(['element', 'round', 'assists', 'bonus', 'bps', 'clean_sheets', 'value',
       'creativity', 'total_points', 'goals_conceded', 'goals_scored',
       'ict_index', 'influence', 'minutes', 'opponent_team', 'red_cards',
       'saves', 'selected_by_percent', 'threat', 'transfers_balance',
       'was_home', 'yellow_cards', 'label', 'player_name', 'web_name',
       'element_type', 'player_team', 'understat_id', 'h_team', 'a_team',
       'shots', 'xG', 'xA', 'key_passes', 'npg', 'npxG', 'xGChain',
       'xGBuildup', 'xG_player_team', 'xGA_player_team', 'npxG_player_team',
       'npxGA_player_team', 'deep_player_team', 'deep_allowed_player_team',
       'scored_player_team', 'missed_player_team', 'npxGD_player_team',
       'ppda_att_player_team', 'ppda_def_player_team',
       'ppda_allowed_att_player_team', 'ppda_allowed_def_player_team',
       'xG_opponent_team', 'xGA_opponent_team', 'npxG_opponent_team',
       'npxGA_opponent_team', 'deep_opponent_team',
       'deep_allowed_opponent_team', 'scored_opponent_team',
       'missed_opponent_team', 'npxGD_opponent_team', 'ppda_att_opponent_team',
       'ppda_def_opponent_team', 'ppda_allowed_att_opponent_team',
       'ppda_allowed_def_opponent_team'],
      dtype='object')

In [28]:
data["minutes"].describe()

count    71597.000000
mean        41.950633
std         41.643897
min          0.000000
25%          0.000000
50%         26.000000
75%         90.000000
max         90.000000
Name: minutes, dtype: float64

In [29]:
data.describe()

,element,round,assists,bonus,bps,clean_sheets,value,creativity,total_points,goals_conceded,...,npxGA_opponent_team,deep_opponent_team,deep_allowed_opponent_team,scored_opponent_team,missed_opponent_team,npxGD_opponent_team,ppda_att_opponent_team,ppda_def_opponent_team,ppda_allowed_att_opponent_team,ppda_allowed_def_opponent_team
count,71597.000000,71597.000000,71597.000000,71597.000000,71597.000000,71597.000000,71597.000000,71597.000000,71597.000000,71597.000000,...,71597.000000,71597.000000,71597.000000,71597.000000,71597.000000,71597.000000,71597.000000,71597.000000,71597.000000,71597.000000
mean,288.261477,20.056413,0.051633,0.136337,7.936667,0.136238,5.316793,6.242633,1.758735,0.638454,...,1.258860,6.659227,6.629783,1.366435,1.362599,0.006071,239.626724,21.613180,240.184728,21.578008
std,168.260302,11.044482,0.248944,0.536360,10.848666,0.336634,1.317538,11.971405,2.837917,1.032617,...,0.795653,4.626346,4.601169,1.236441,1.235506,1.301102,88.624683,6.465405,88.796477,6.479617
min,1.000000,1.000000,0.000000,0.000000,-19.000000,0.000000,3.800000,0.000000,-6.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,-5.524602,58.000000,4.000000,58.000000,4.000000
25%,143.000000,11.000000,0.000000,0.000000,0.000000,0.000000,4.500000,0.000000,0.000000,0.000000,...,0.658980,3.000000,3.000000,0.000000,0.000000,-0.835011,174.000000,17.000000,174.000000,17.000000
50%,286.000000,20.000000,0.000000,0.000000,3.000000,0.000000,4.900000,0.200000,1.000000,0.000000,...,1.118500,6.000000,6.000000,1.000000,1.000000,0.003451,230.000000,21.000000,232.000000,21.000000
75%,429.000000,30.000000,0.000000,0.000000,14.000000,0.000000,5.600000,8.000000,2.000000,1.000000,...,1.703660,9.000000,9.000000,2.000000,2.000000,0.853572,295.000000,26.000000,296.000000,25.394737
max,680.000000,38.000000,22.500000,3.000000,382.500000,1.451613,13.600000,321.750000,90.000000,10.000000,...,5.869320,35.000000,35.000000,9.000000,9.000000,5.524602,628.000000,55.000000,628.000000,55.000000

In [30]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71597 entries, 0 to 71596
Data columns (total 64 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   element                         71597 non-null  int64
 1   round                           71597 non-null  int64
 2   assists                         71597 non-null  float64
 3   bonus                           71597 non-null  float64
 4   bps                             71597 non-null  float64
 5   clean_sheets                    71597 non-null  float64
 6   value                           71597 non-null  float64
 7   creativity                      71597 non-null  float64
 8   total_points                    71597 non-null  float64
 9   goals_conceded                  71597 non-null  float64
 10  goals_scored                    71597 non-null  float64
 11  ict_index                       71597 non-null  float64
 12  influence                       71597 non-null  float64
 13  minutes                         71597 non-null  float64
 14  opponent_team                   71597 non-null  object
 15  red_cards                       71597 non-null  float64
 16  saves                           71597 non-null  float64
 17  selected_by_percent             71597 non-null  float64
 18  threat                          71597 non-null  float64
 19  transfers_balance               71597 non-null  int64
 20  was_home                        71597 non-null  int64
 21  yellow_cards                    71597 non-null  float64
 22  label                           71597 non-null  int64
 23  player_name                     71597 non-null  object
 24  web_name                        71597 non-null  object
 25  element_type                    71597 non-null  int64
 26  player_team                     71597 non-null  object
 27  understat_id                    71597 non-null  int64
 28  h_team                          71597 non-null  object
 29  a_team                          71597 non-null  object
 30  shots                           71597 non-null  float64
 31  xG                              71597 non-null  float64
 32  xA                              71597 non-null  float64
 33  key_passes                      71597 non-null  float64
 34  npg                             71597 non-null  float64
 35  npxG                            71597 non-null  float64
 36  xGChain                         71597 non-null  float64
 37  xGBuildup                       71597 non-null  float64
 38  xG_player_team                  71597 non-null  float64
 39  xGA_player_team                 71597 non-null  float64
 40  npxG_player_team                71597 non-null  float64
 41  npxGA_player_team               71597 non-null  float64
 42  deep_player_team                71597 non-null  float64
 43  deep_allowed_player_team        71597 non-null  float64
 44  scored_player_team              71597 non-null  float64
 45  missed_player_team              71597 non-null  float64
 46  npxGD_player_team               71597 non-null  float64
 47  ppda_att_player_team            71597 non-null  float64
 48  ppda_def_player_team            71597 non-null  float64
 49  ppda_allowed_att_player_team    71597 non-null  float64
 50  ppda_allowed_def_player_team    71597 non-null  float64
 51  xG_opponent_team                71597 non-null  float64
 52  xGA_opponent_team               71597 non-null  float64
 53  npxG_opponent_team              71597 non-null  float64
 54  npxGA_opponent_team             71597 non-null  float64
 55  deep_opponent_team              71597 non-null  float64
 56  deep_allowed_opponent_team      71597 non-null  float64
 57  scored_opponent_team            71597 non-null  float64
 58  missed_opponent_team            71597 non-null  float64
 59  npxGD_opponent_team             71597 non-null  float64
 60  ppda_att_opponent_team          71597 non-null  float64
 61  ppda_def_opponent_team          71597 non-null  float64
 62  ppda_allowed_att_opponent_team  71597 non-null  float64
 63  ppda_allowed_def_opponent_team  71597 non-null  float64
dtypes: float64(51), int64(7), object(6)
memory usage: 35.0+ MB

In [31]:
data["player_name"]

0        Aaron Cresswell
1        Aaron Cresswell
2        Aaron Cresswell
3        Aaron Cresswell
4        Aaron Cresswell
              ...
71592       Ørjan Nyland
71593       Ørjan Nyland
71594       Ørjan Nyland
71595       Ørjan Nyland
71596       Ørjan Nyland
Name: player_name, Length: 71597, dtype: object

In [32]:
columns = ["player_name","total_points"]
data[columns]

           player_name  total_points
0      Aaron Cresswell      3.611949
1      Aaron Cresswell      0.000000
2      Aaron Cresswell      0.000000
3      Aaron Cresswell      0.000000
4      Aaron Cresswell      0.000000
...                ...           ...
71592     Ørjan Nyland      0.000000
71593     Ørjan Nyland      0.000000
71594     Ørjan Nyland      0.000000
71595     Ørjan Nyland      0.000000
71596     Ørjan Nyland      0.000000

[71597 rows x 2 columns]